### ISSUE TITLE
BLE Scan does not work on Android 12 when Screen is OFF

### ISSUE THREAD

**Issue by asifmahmood2022** [kkmhogen/KBeaconProDemo_Android#1]
Hi we are trying to scan from background service and our application has all the permissions required by Android 12 
as long as screen is on background service is able to find the W7 tether but as soon as we turn off the screen scanning not able to find any device.

**Comment by kkmhogen** [comment]
This may be determined by the mechanism of Android, where the app starts Bluetooth scanning in the background. The Android system may intermittently scan according to the system's policies.
Additionally, you may need to start a foreground service and then initiate scanning within the service.
