### ISSUE TITLE
Minimum battery percentage of Beacon 

### ISSUE THREAD

**Issue by pravingws** [kkmhogen/KBeaconProDemo_Android#10]
What should be the minimum battery % of Kbeacon to make sure that it is working 100% as expected in terms of Advertisements and Button clicks etc. 

Or it will always perform best till it goes to 0% battery ?

**Comment by kkmhogen** [comment]
For beacons with coin cell batteries, our 0% voltage is 2.5V. If the broadcast interval of the beacon is 1 second, the beacon should still work for a period of time, usually more than a few days.
