### ISSUE TITLE
KBeacon object doesn't have Serial Number info printed on the Physical Beacon.

### ISSUE THREAD

**Issue by pravingws** [kkmhogen/KBeaconProDemo_Android#11]
I am scanning the available beacons using KBeacon library.
`KBeaconsMgr.KBeaconMgrDelegate - onBeaconDiscovered
`
This doesn't returns the SERIAL NUMBER info. How to get the serial number from the scanned KBeacons ?

Note: We are able to fetch the SERIAL ID from by reading the QR code available on the beacon device.

**Comment by kkmhogen** [comment]
Thank you for your suggestion. Our new Beacon version now supports reading Serial IDs. Please upgrade the Beacon firmware to 6.67 or higher. You can obtain the Serial ID through the following methods:
KBCfgCommon cfgCommon = mBeacon.getCommonCfg();
Integer serialID = cfgCommon.getSerialNo();
