### ISSUE TITLE
Require React Native Library

### ISSUE THREAD

**Issue by KushEvent** [kkmhogen/KBeaconProDemo_Android#13]
Do you guys have library for react native?

I have to implement in one of my project.

**Comment by kkmhogen** [comment]
Sorry, we currently do not have a React Native library. If you are developing using React Native, please contact our sales team to provide the Bluetooth API, which may require you to implement the library yourself.

**Comment by devSoftlogicx** [comment]
@KushEvent have u managed to implement beacon scanner in react-native?

**Comment by KushEvent** [comment]
Not yet with this library....

**Comment by devSoftlogicx** [comment]
> Not yet with this library....

any other recommendation?

**Comment by KushEvent** [comment]
yes I'm using react-native-ble-manager for scanning the data

**Comment by devSoftlogicx** [comment]
> yes I'm using react-native-ble-manager for scanning the data

i have already used this pkg, it detects bluetooth devices around but not the iBeacons

**Comment by KushEvent** [comment]
for that we have specifically do a code at native level for both the platform

which iBeacons u are used
