### ISSUE TITLE
Power Off section is out of date

### ISSUE THREAD

**Issue by f1234k** [kkmhogen/KBeaconProDemo_Android#3]
In the [Power Off section](https://github.com/kkmhogen/KBeaconProDemo_Android#4372-power-off-device) you create a JSONObject and yet the sendCommand method of the beacon is expecting a Hashmap<String, Object>. 

What is the proper command to power off the device?

**Comment by f1234k** [comment]
After further research, I think your example code should look a bit like this:

```
JSONObject cmdPara = new JSONObject();
try {
    cmdPara.put("msg", "admin");
    cmdPara.put("stype", "pwroff");
}
catch (JSONException except)
{
    toastShow("Failed to poweroff: " + beacon.getMac() + ". Reason: " + except);
    return;
}
HashMap<String, Object> cmdParaHashMap = new HashMap<>();
KBCfgBase.JsonObject2HashMap(cmdPara, cmdParaHashMap);
beacon.sendCommand(cmdParaHashMap, (bConfigSuccess1, error1) -> {
```
...

**Comment by kkmhogen** [comment]
Thank you for your suggestion, we have made revisions.
