### ISSUE TITLE
Missing eddystonedemo?

### ISSUE THREAD

**Issue by christopherraa** [kkmhogen/KBeaconProDemo_Android#4]
The readme-file in this repository mentions `eddystonedemo` but I cannot see that present here. `sensordemo` and `ibeacondemo` are present, but not the mentioned `eddystonedemo`. Is this to be added at a later time?

**Comment by christopherraa** [comment]
I see now that the repository `kkmhogen/KBeaconDemo_Android` _has_ the eddystonedemo, but this repo does not. Perhaps the readme of this repo should be updated?

**Comment by kkmhogen** [comment]
Thank you for your feedback, we've added a demo.

**Comment by christopherraa** [comment]
Very nice! Thanks for following up on this. Have a great day.
