### ISSUE TITLE
How to configure LED colors for IBeacon?

### ISSUE THREAD

**Issue by pravingws** [kkmhogen/KBeaconProDemo_Android#5]
Is there any provision to configure LED light color on KBeacon device? 
If not, then can we at least configure the duration of Blue LED colour on the Panic device. Let’s say, keep BLUE LED light always on when the Panic Device is turned on.

We tried following: (Not working)

           ```

            cmdPara.put("ringTime", 3000) // ring times, uint is ms , shoul be 3k or +

            cmdPara.put("ringType", 0x2) // 0x2:led flash only; 0x1:beep alert only;

            cmdPara.put("ledOn", 200) // valid when ringType set to 0x0 or 0x2

            cmdPara.put("ledOff", 1800) //valid when ringType set to 0x0 or 0x2

            cmdPara.put("ledColor", "green") //valid when ringType set to 0x0 or 0x2
```

**Comment by kkmhogen** [comment]
Sorry, Beacon does not yet support specifying flashing colors.
Also, do you mean the LED light stays on continuously after the device is turned on? This may consume a lot of batteries. Of course, we also support custom firmware. Please contact our sales team.
