### ISSUE TITLE
Battery consumption if Beacon "Always On" mode is enabled?

### ISSUE THREAD

**Issue by pravingws** [kkmhogen/KBeaconProDemo_Android#6]
Currently, KBeacon promises battery backup of around 30+ days. What will be the battery backup if I enable "Always On" mode in the IBeacon ?

So, What will be the battery life if we keep device connected 24*7 for 7 days in “Always On” mode?

**Comment by kkmhogen** [comment]
Hello, setting Always On does not result in an increase in power consumption.  After this function is enabled, it is not allowed to turn off the computer by pressing and holding the button.
