### ISSUE TITLE
Want to test Battery Consumption for specific scenerio.

### ISSUE THREAD

**Issue by pravingws** [kkmhogen/KBeaconProDemo_Android#8]
If I want to explicity (intentionally) drain the battery faster or say increase the battery consumption and make the device turn off due to low battery then what parameter do I need to set?

**Comment by kkmhogen** [comment]
You can increase the broadcast frequency, such as setting the device to broadcast every 100ms, enabling 5 slots with a broadcast interval of 100ms for each slot, and setting the Tx power to the maximum. This can accelerate battery consumption, and it depends on which specific product you are using. Some products have larger battery capacities, so the testing process may be longer.
Another way is to connect the positive and negative poles of the beacon through the power supply, and then adjust the output voltage of the power supply to trigger the low power automatic shutdown.
